// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkeXi-IUGcWvGJPxuF7SqJiiDwyOIpqOE',
    appId: '1:637623458203:web:1dad1885ba882c1aed693e',
    messagingSenderId: '637623458203',
    projectId: 'jobapp-10cac',
    authDomain: 'jobapp-10cac.firebaseapp.com',
    storageBucket: 'jobapp-10cac.appspot.com',
    measurementId: 'G-YDDYL7GKP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_RX25VLmjyOHcOvar2gatvXA57zJIML0',
    appId: '1:637623458203:android:35631f62d753cdb7ed693e',
    messagingSenderId: '637623458203',
    projectId: 'jobapp-10cac',
    storageBucket: 'jobapp-10cac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBr5tt1vNrsVv1zNj7rqstJQ6bN5d8VGM',
    appId: '1:637623458203:ios:69f4052fe20ce8a4ed693e',
    messagingSenderId: '637623458203',
    projectId: 'jobapp-10cac',
    storageBucket: 'jobapp-10cac.appspot.com',
    iosClientId: '637623458203-bbepkj7bjv9qdl6mqifvbrk3ha5cr8vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsyV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBr5tt1vNrsVv1zNj7rqstJQ6bN5d8VGM',
    appId: '1:637623458203:ios:69f4052fe20ce8a4ed693e',
    messagingSenderId: '637623458203',
    projectId: 'jobapp-10cac',
    storageBucket: 'jobapp-10cac.appspot.com',
    iosClientId: '637623458203-bbepkj7bjv9qdl6mqifvbrk3ha5cr8vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsyV2',
  );
}
